<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.ApiEndpoints" Version="4.1.0" />
    <PackageReference Include="Cortex.Mediator" Version="3.1.2" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
	<PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brutiquzz.VerticalSlice.DataAccess\Brutiquzz.VerticalSlice.DataAccess.csproj" />
  </ItemGroup>

</Project>
